version: 2

defaults: &defaults
  working_directory: /go/src/github.com/mercari/grpc-http-proxy
  resource_class: medium+

golang: &golang
  <<: *defaults
  docker:
    - image: golang:1.11-stretch

jobs:
  build:
    <<: *golang
    steps:
    - checkout
    - run:
        name: set credentials with ${GITHUB_TOKEN} from CI's context
        command: |
          echo "machine github.com login ${GITHUB_TOKEN}" > ~/.netrc
          if [ -f ~/.gitconfig ]; then rm ~/.gitconfig; fi
    - run:
        name: Install dependencies and vendor
        command: |
          go get -u github.com/golang/dep/cmd/dep
          make dep
    - run:
        name: Run test
        command: |
          make test
    - run:
        name: Run coverage
        command: |
          make coverage
          bash <(curl -s https://codecov.io/bash)
  lint:
    <<: *golang
    steps:
    - checkout
    - run:
        name: set credentials with ${GITHUB_TOKEN} from CI's context
        command: |
          echo "machine github.com login ${GITHUB_TOKEN}" > ~/.netrc
          if [ -f ~/.gitconfig ]; then rm ~/.gitconfig; fi
    - run:
        name: Install dependencies and vendor
        command: |
          go get -u github.com/golang/dep/cmd/dep
          make dep
    - run:
        name: Run lint
        command: |
          make reviewdog
workflows:
  version: 2
  build-workflow:
    jobs:
    - build:
        context: org-global
    - lint:
        context: org-global
